# Generated by Django 5.2.7 on 2025-10-09 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VesselData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vessel_name', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('hire_rate', models.IntegerField()),
                ('market_rate', models.IntegerField()),
            ],
        ),
    ]
